import type { GuidedChoiceTaskConfig } from '../../components/assessment/GuidedChoiceTask'

const items = [
  { id: 1, word: 'usually', full: 'I usually do my homework after dinner.', sentence: <>I <b>[A]</b> do <b>[B]</b> my homework <b>[C]</b> after dinner.</>, hints: ['Find the main verb: do.', 'Frequency words like usually normally go before the main verb.'] },
  { id: 2, word: 'often', full: 'Lan often uses the computer room at break time.', sentence: <>Lan <b>[A]</b> uses <b>[B]</b> the computer room <b>[C]</b> at break time.</>, hints: ['Find the main verb: uses.', 'Often goes before the main verb.'] },
  { id: 3, word: 'usually', full: 'We do not usually have lessons on Saturday.', sentence: <>We do not <b>[A]</b> have <b>[B]</b> lessons <b>[C]</b> on Saturday.</>, hints: ['The sentence already has do not. Find the main verb: have.', 'In this negative sentence, usually goes after do not and before the main verb.'] },
  { id: 4, word: 'sometimes', full: 'Does Minh sometimes have lunch at school?', sentence: <>Does Minh <b>[A]</b> have <b>[B]</b> lunch <b>[C]</b> at school?</>, hints: ['This is a question. Find the main verb: have.', 'Sometimes goes after the subject Minh and before the main verb.'] },
]

export const TASK_60133_CONFIG = {
  className: 'task-60133', intro: <><strong>Check Task 3.</strong><br />Enter the A, B or C positions you chose in the worksheet.</>, entryTitle: 'Your worksheet choices', entrySubtitle: '4 items', entryNote: 'The thinking happens on the worksheet. The app only records A/B/C and gives help if the position is wrong.', options: ['A', 'B', 'C'],
  items: items.map((item) => ({ id: item.id, key: 'A', firstHint: item.hints[0], secondHint: item.hints[1], retryTag: 'FREQUENCY-POSITION', bookCue: <>Place <strong>{item.word}</strong> in the correct slot.</>, summaryLabel: `Question ${item.id}`, retryContent: <><div className="sentence">{item.sentence}</div><div className="target-word">{item.word}</div></>, correctedNotice: `Full sentence: ${item.full}` })),
  demoAnswers: { 1: 'A', 2: 'B', 3: 'C', 4: 'A' }, incompleteMessage: 'Choose A, B or C for all 4 items first.', itemSingular: 'Question', itemPlural: 'Questions', retryDataAttribute: 'question', resultsTitle: 'Task 3 check', summaryTitle: 'Task 3 complete ✓', summarySubtitle: 'Adverb position', evidenceTag: 'FREQUENCY-POSITION', evidenceNote: 'The app stores first-attempt errors under FREQUENCY-POSITION. Full-sentence writing stays in later worksheet tasks.', footerIdle: 'Check 4 answers.', footerComplete: 'Continue to Task 4.', continueLabel: 'Task 4', completeIndependent: 'You can now place frequency words in the right position. Back to your book for Task 4.', completeGuided: 'You can now place frequency words in the right position. Back to your book for Task 4.', backMessage: 'Keep going. I’ll be here when you need me.', maxAttempts: 2, guidedAtLimit: false, summaryMode: 'answers', celebration: true,
} satisfies GuidedChoiceTaskConfig
