import { expect, test } from '@playwright/test'

async function fillRetry(page: import('@playwright/test').Page, values: string[]) {
  const retry = page.locator("[data-stage='retry']")
  for (let index = 0; index < values.length; index += 1) await retry.locator(`[data-retry-part='${index}']`).fill(values[index])
  await retry.locator('[data-retry-check]').click()
}

test('60131 preserves validation, retries, transfers and completion', async ({ page }) => {
  await page.route('https://dl.dropboxusercontent.com/**', (route) => route.fulfill({ status: 200, contentType: 'image/gif', body: Buffer.from('R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==', 'base64') }))
  await page.goto('/tasks/60131')
  await expect(page.locator(".task-60131[data-module-ready='true']")).toBeVisible()
  await page.locator('[data-check]').click()
  await expect(page.getByText('Complete all 8 answers first.')).toBeVisible()
  await page.locator('[data-demo]').click()
  await page.locator('[data-check]').click()
  await expect(page.getByText('Questions 2 need a quick fix.')).not.toBeVisible()
  await expect(page.getByText(/Questions\s+2, 8\s+need a quick fix/)).toBeVisible()
  await expect(page.locator("[data-question='2'][data-attempt='1']")).toBeVisible()
  await fillRetry(page, ['go'])
  await expect(page.getByText('Not yet.')).toBeVisible()
  await expect(page.locator("[data-question='2'][data-attempt='2']")).toBeVisible()
  await fillRetry(page, ['goes'])
  await expect(page.getByText('Correct ✓', { exact: true }).last()).toBeVisible()
  await expect(page.locator("[data-question='8'][data-attempt='1']")).toBeVisible()
  await fillRetry(page, ['Does', 'likes'])
  await expect(page.locator("[data-question='8'][data-attempt='2']")).toBeVisible()
  await fillRetry(page, ['Do', 'likes'])
  await expect(page.getByText('Correct form: Does … like.')).toBeVisible()
  let transfer = page.locator("[data-stage='transfer'][data-tag='FORM-AGREEMENT']")
  await expect(transfer).toBeVisible()
  await transfer.locator("[data-option='go']").click()
  await expect(page.getByText('Not yet. Use the same rule you just reviewed.')).toBeVisible()
  await expect(page.getByText('Not yet. Use the same rule you just reviewed.')).toBeHidden()
  await transfer.locator("[data-option='goes']").click()
  transfer = page.locator("[data-stage='transfer'][data-tag='FORM-AUXILIARY']")
  await expect(transfer).toBeVisible()
  await transfer.locator("[data-option='Does / play']").click()
  await expect(page.locator("[data-stage='complete']")).toBeVisible()
  await expect(page.locator('#backBook')).toBeEnabled()
  await page.locator('[aria-label="Open number keypad"]').click()
  await expect(page.locator('.pin-slot')).toHaveCount(5)
})
