import { expect, test, type Locator, type Page } from '@playwright/test'
async function autoRecord(card:Locator){await card.locator('[data-record]').click();await expect(card.locator('.transcript, .feedback, .colloc').first()).toBeVisible({timeout:4_000})}
test.beforeEach(async({page})=>{await page.route('https://dl.dropboxusercontent.com/**',route=>route.fulfill({status:200,contentType:'image/gif',body:Buffer.from('R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==','base64')}))})
test.setTimeout(90_000)

test('60121 keeps collocation retries and transfer',async({page})=>{await page.goto('/tasks/60121');await page.locator('#demo').click();await page.locator('#check').click();let card=page.locator("[data-stage='retry']");await card.locator("[data-option='play']").click();await expect(card).toContainText('Not yet.');await page.waitForTimeout(600);await card.locator("[data-option='do']").click();await page.waitForTimeout(600);card=page.locator("[data-stage='retry']");await card.locator("[data-option='do']").click();await page.waitForTimeout(600);await page.locator("[data-stage='transfer'] [data-option='do']").click();await expect(page.getByText('Task 1 complete ✓')).toBeVisible();await expect(page.locator('#backBook')).toBeEnabled()})
test('60122 completes Book-first focused meaning retries',async({page})=>{await page.goto('/tasks/60122');await page.locator('[data-demo]').click();await page.locator('[data-check]').click();for(const [id,value] of [[3,'C'],[5,'B']] as const){const card=page.locator(`[data-stage='retry'][data-question='${id}']`);await expect(card).toContainText(`Question ${id}`);await expect(card.locator('.question, .option-text')).toHaveCount(0);await expect(card.locator('[data-option]')).toHaveCount(3);await card.locator(`[data-option='${value}']`).click()}await expect(page.locator("[data-stage='complete']")).toBeVisible()})
test('60123 completes listening repair and pronunciation sequence',async({page})=>{await page.goto('/tasks/60123');await page.locator('[data-play-sequence]').click();await expect(page.getByText('Played 1 / 2')).toBeVisible();await page.locator('[data-play-again]').click();await expect(page.getByText('Played 2 / 2')).toBeVisible();await page.locator('[data-enter-answers]').click();await page.locator('[data-demo]').click();await page.locator('[data-check-listening]').click();let repair=page.locator("[data-stage='repair-listening']");await repair.locator("[data-sound='/ɑː/']").click();await page.waitForTimeout(700);repair=page.locator("[data-stage='repair-listening']");await repair.locator("[data-sound='/ʌ/']").click();for(const word of ['art','class','start','smart','subject','study','Monday','lunch']){let card=page.locator("[data-stage='pronunciation']").last();await card.locator('[data-record]').click();if(word==='class'||word==='Monday'){await expect(card.getByText('Almost there.')).toBeVisible();await card.locator('[data-retry-record]').click();card=page.locator("[data-stage='pronunciation']").last();await card.locator('[data-record]').click()}if(word!=='lunch')await page.waitForTimeout(2_300)}await expect(page.locator("[data-stage='complete']")).toBeVisible({timeout:5_000})})
test('60124 keeps required second-sentence retry',async({page})=>{await page.goto('/tasks/60124');for(const n of [1,2,3,4]){let card=page.locator(`[data-stage='sentence'][data-sentence='${n}']`).last();await autoRecord(card);if(n===2){await expect(card.getByText('Almost there.')).toBeVisible();await card.locator('[data-retry]').click();card=page.locator(`[data-stage='sentence'][data-sentence='2']`).last();await autoRecord(card)}await card.locator('[data-next]').click()}await expect(page.locator("[data-stage='complete']")).toBeVisible()})
test('60125 keeps ASR and written-error branches',async({page})=>{await page.goto('/tasks/60125');let card=page.locator("[data-stage='capture'][data-sentence='1']").last();await autoRecord(card);await card.locator('[data-confirm]').click();card=page.locator("[data-stage='capture'][data-sentence='2']").last();await autoRecord(card);await card.locator('[data-asr]').click();card=page.locator("[data-stage='capture'][data-sentence='2']").last();await autoRecord(card);await card.locator('[data-written]').click();card=page.locator("[data-stage='capture'][data-sentence='2'][data-retry-mode='true']");await autoRecord(card);await card.locator('[data-confirm]').click();card=page.locator("[data-stage='capture'][data-sentence='3']").last();await autoRecord(card);await card.locator('[data-confirm]').click();await page.locator('[data-done]').click();await expect(page.locator("[data-stage='complete']")).toBeVisible()})
async function finishReview(page:Page){await page.locator('[data-start]').click();for(const [i,v] of [['1','do'],['2','do'],['3','study']]){const card=page.locator(`[data-stage='review'][data-review='${i}']`);await card.locator(`[data-option='${v}']`).click();await page.waitForTimeout(700)}}
test('60126 applies the 4/5 mastery gate',async({page})=>{await page.goto('/tasks/60126');await finishReview(page);for(const [i,v] of [['1','play'],['2','study'],['3','do'],['4','play'],['5','play']]){await page.locator(`[data-stage='mastery'][data-mastery='${i}'] [data-option='${v}']`).click();await page.waitForTimeout(700)}await expect(page.locator("[data-stage='mastery-pass']")).toBeVisible();await expect(page.locator('#backBook')).toBeEnabled()})
