import { useState } from 'react'
import type { TaskComponentProps } from '../../app/task-types'
import { ChoiceGroup } from '../../components/answers/ChoiceGroup'
import { Celebration } from '../../components/effects/Celebration'
import { MasteryGate } from '../../components/progress/MasteryGate'
import { ProgressSteps } from '../../components/progress/ProgressSteps'
import { ScoreGrid } from '../../components/progress/ScoreGrid'
import { StatusFooter } from '../../components/shell/StatusFooter'
import { ActionButton } from '../../components/task/ActionButton'
import { useTaskTimers } from '../../hooks/useTaskTimers'
import { TaskRenderer } from '../../task-engine/TaskRenderer'
import type { TaskFlowBlock } from '../../task-engine/schema'
import { MASTERY_60126, REVIEW_60126 } from './data'

export function Task60126({ task }: TaskComponentProps) {
  const [phase,setPhase]=useState<'intro'|'review'|'mastery'|'done'>('intro'); const [index,setIndex]=useState(0); const [score,setScore]=useState(0); const [answers,setAnswers]=useState<boolean[]>([]); const [feedback,setFeedback]=useState(''); const [notices,setNotices]=useState<string[]>([])
  const schedule = useTaskTimers()
  const pass=phase==='done'&&score>=4
  const choose=(value:string)=>{ if(feedback)return; const item=phase==='review'?REVIEW_60126[index]:MASTERY_60126[index]; const correct=value===item.key; setFeedback(correct?'Correct ✓':phase==='review'?'Not yet. Think about which verb normally goes with this noun phrase.':'Not correct. This answer is recorded. No hint is given in the mastery check.'); if(phase==='review'&&!correct){schedule(()=>setFeedback(''),700);return} schedule(()=>{setFeedback('');if(phase==='review'){if(index===2){setPhase('mastery');setIndex(0);setNotices(v=>[...v,'Review complete ✓ Now try 5 new collocation items. No hints this time.'])}else setIndex(v=>v+1)}else{setAnswers(v=>[...v,correct]);if(correct)setScore(v=>v+1);if(index===4)setPhase('done');else setIndex(v=>v+1)}},650)}
  const active=phase==='review'?REVIEW_60126[index]:phase==='mastery'?MASTERY_60126[index]:null
  const blocks:TaskFlowBlock[]=[{id:'intro-msg',type:'tutor-message',content:<><strong>Task 6.</strong><br/>First, let’s review a few collocations that needed extra help. Then you’ll do a short mastery check with new items.</>},...notices.map((n,i):TaskFlowBlock=>({id:`n-${i}`,type:'tutor-message',content:n})),...(phase==='intro'?[{id:'intro',type:'panel' as const,title:'Priority review',subtitle:'3 targets',stage:'review-intro',content:<><div className="note">These are the collocations that were not correct on the first attempt earlier in WS2. The system prioritises higher retry counts first.</div><div className="target-list">{REVIEW_60126.map((x,i)=><span className="target hot" key={x.label}>{i+1}. {x.label}</span>)}</div><div className="actions"><ActionButton variant="secondary" data-why onClick={()=>setNotices(v=>[...v,'The system uses first-attempt errors and retry history. A final corrected answer does not automatically count as independent mastery.'])}>Why these?</ActionButton><ActionButton data-start onClick={()=>setPhase('review')}>Start review</ActionButton></div></>}] : []),...(active?[{id:`active-${phase}-${index}`,type:'custom' as const,content:<section className="card" data-stage={phase} data-review={phase==='review'?index+1:undefined} data-mastery={phase==='mastery'?index+1:undefined}><div className="ch"><h2>{phase==='review'?`Review ${index+1}`:'Mastery Check'}</h2><span>{index+1} / {phase==='review'?3:5}</span></div><div className="cb">{phase==='mastery'?<ProgressSteps steps={MASTERY_60126.map((_,i)=>({id:String(i),label:String(i+1),status:i<index?'complete':i===index?'active':'pending'}))}/>:null}<div className="q">{active.q}</div><ChoiceGroup ariaLabel="Collocation answer" options={active.opts.map(x=>({value:x,label:x}))} onChange={choose}/><div className={feedback.includes('Correct')?'feedback ok':'feedback warn'}>{feedback}</div></div></section>}] : []),...(phase==='done'?[{id:'result',type:'custom' as const,content:<section className={pass?'summary':'card'} data-stage={pass?'mastery-pass':'mastery-practice'}><div className="ch"><h2>{pass?'Mastery reached ✓':'More practice needed'}</h2><span>{score} / 5</span></div><div className="cb"><ScoreGrid items={answers.map((correct,i)=>({id:String(i),label:`Item ${i+1}`,value:correct?'Correct ✓':'Incorrect',tone:correct?'success':'error'}))}/><MasteryGate mastered={pass} title={pass?'Mastery reached ✓':'Targeted practice needed'}>{pass?'You answered at least 4 of 5 unseen collocation items correctly without hints.':'Your score is below 4/5. The system should assign targeted collocation practice.'}</MasteryGate></div></section>},{id:'celebrate',type:'custom' as const,content:<Celebration active={pass}/>}]:[])];
  return <TaskRenderer task={task} className="task-60126 mastery-task" footer={<StatusFooter title={pass?'WS2 complete':'Task 6'} status={phase==='done'?(pass?'Mastery reached':'Targeted practice needed'):phase==='mastery'?`Mastery ${index+1} of 5`:phase==='review'?`Review ${index+1} of 3`:'Priority review'} actionLabel="Worksheet finished" actionId="backBook" disabled={phase!=='done'} onAction={()=>setNotices(v=>[...v,'Nice work. This worksheet is complete.'])}/>} blocks={blocks}/>
}
